var userClickedPattern=[];//track the pattern on which user has clicked

var buttonColors=["red", "blue", "green", "yellow" ];//the array that contains the colors of the button that we have in the game
var gamePattern=[];//track the sequence that is generated by the computer

var started = false;//started variable is toggled to true and fase to checkl whether to play the game or end it
var level=0;//detects the level of the game
//to detect whether a key is pressed by the user.if strted==True then nextsequence will be called
$(document).on('keypress',function(e) {
    if(!started){
        $("#level-title").text("Level " + level);
        nextSequence();
        started=true;
    }
});

//to generate the sequence that user hads to follow
function nextSequence(){
    userClickedPattern=[];//makes tbhe user clicked pattern to empty as user will start clicking now
    var randomNumber=Math.floor(Math.random()*4);//stores random no from 0 to 4
    randomChosenColour=buttonColors[randomNumber];//acc to randomNumber it selects a color from array buttonColors
  
    gamePattern.push(randomChosenColour);//stores the random color generated into a this array which keeps the track whicvh color pattern is generated by the function

    $('#'+randomChosenColour).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100);//shows anmimations when a sequence is generated
    playsound(randomChosenColour);//apply sound to the pressed button

    level=level+1;//indicates the level of the game
    $("#level-title").text("Level " + level);
}

//tracks the event(clicked on the button) by the player
$(".btn").click(function( ){
    var userChosenColour=$(this).attr("id");//saves the id of the button presses

    userClickedPattern.push(userChosenColour);//array that contains the pattern that user has clicked
    
    playsound(userChosenColour);//applyimg sound to the clicked buttons
    animatePress(userChosenColour);//applying animation to the clicked buttons
    checkAnswer(userClickedPattern.length-1)
});


//function to play sound when button is clicked
function playsound(name){
    var audio=new Audio('./sounds/'+name+'.mp3');
    audio.play();
}

//function to create animation on the button pressed
function animatePress(currentColour){
    $("#"+currentColour).addClass("pressed");
    //timeout function that will remove the animations after 500millisecond
    setTimeout(function(){
        $("#"+currentColour).removeClass("pressed");
    },500);
}

//function that checks the answer i.e the pattern generated by the game(gamePattern) is equal to the pattern clicked by the user(userClickedPatter)
function checkAnswer(currentLevel){
    if(gamePattern[currentLevel]===userClickedPattern[currentLevel]){

        console.log("success");

        if(gamePattern.length===userClickedPattern.length){
            setTimeout(nextSequence,1000);
           
        }
    }
    else{
        console.log("wrong");
        var wrong=new Audio('./sounds/wrong.mp3');
        wrong.play();
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        },500);
        $("h1").text("Game Over, Press Any Key to Restart");
        startover();
    }
}

//if sequence gois gone wrong then in case we have to restart the game
function startover(){
    level=0;
    started=false;
    gamePattern=[];
}







